language: node_js
node_js:
- '4.6'
- '6.10'
deploy:
  provider: npm
  email: mg@localz.co
  api_key: ${NPM_TOKEN}
  on:
    tags: true
    branch: master
    node: '6.10'    
    repo: localz/srv-request